### PR TITLE
E2214. Refactor teams_controller.rb

### PR DESCRIPTION
**Pull request by vishnuchalla**
We suggest you including the below information in your pull request:
- Made success message meaningfull in create_teams method.
- Fixed an indentation error in one of the previous commits.
---
About Expertiza Bot
- If you have any questions about comments given by the expertiza-bot [(example)](https://github.com/expertiza/expertiza/pull/1877#issuecomment-762412918), you could create a comment in your pull request with the format `/dispute [UUID1] [UUID2]` [(example)](https://github.com/expertiza/expertiza/pull/1877#issuecomment-762430057) then the professor and TAs will be notified.
- [Here is a video](https://tinyurl.com/internet-bots) about how to communicate to expertiza-bot.

### CODE REVIEW

**Review by vishalveerareddy — APPROVED** [review]

**Comment by vishalveerareddy** [comment]
Build is still failing please check and merge.

**Review by kellyfleming — COMMENTED** [review]
The changes to Gemfile, controller, model, and tree_display template all look good.
Line 785 and 786 seem to have actual changes in the db/schema file. Do we want that in beta?

**Review by kellyfleming — APPROVED** [review]

**Review by kellyfleming — COMMENTED** [review]
Rubocop appears to be failing differently now. An issue with running Ruby, I think?

**Comment by vishnuchalla** [comment]
> The changes to Gemfile, controller, model, and tree_display template all look good. Line 785 and 786 seem to have actual changes in the db/schema file. Do we want that in beta?

Thanks for bringing it up. It came up while merging from expertiza/expertiza "beta" branch. But as a best practice, I have reset that file.

**Comment by vishnuchalla** [comment]
> Rubocop appears to be failing differently now. An issue with running Ruby, I think?

The existing rubocop in the dependency graph has bug which does not understand an early return in the code. Related issue thread and fix: https://tinyurl.com/mbrt3pjd. In future expertiza needs to upgrade rubocop to 1.26.1 version in order to fix the rubocop fix. It requires good amount of bandwidth as it may lead to lot many breaking changes in the existing dependency graph. So i have mentioned the details in the commnets section as TODO action in future.

**Comment by vishnuchalla** [comment]
> Build is still failing please check and merge.

It's due to rubocop. Mentioned the details above.

**Comment by vishnuchalla** [comment]
> Build is still failing please check and merge.

It's due to rubocop. Mentioned the details above.

**Comment by vishnuchalla** [comment]
Merging the code changes into beta.

**Pull request merged**
