### PR TITLE
Added function search_params and test case .

### PR DESCRIPTION
**Pull request by sujith3179**
E2233. Improvising search facility in expertiza

Added a function - search_params  for advanced search functionality.
Added test case for search params function implemented for advanced search functionality.

About Expertiza Bot
- If you have any questions about comments given by the expertiza-bot [(example)](https://github.com/expertiza/expertiza/pull/1877#issuecomment-762412918), you could create a comment in your pull request with the format `/dispute [UUID1] [UUID2]` [(example)](https://github.com/expertiza/expertiza/pull/1877#issuecomment-762430057) then the professor and TAs will be notified.
- [Here is a video](https://tinyurl.com/internet-bots) about how to communicate to expertiza-bot.

### CODE REVIEW

**Comment by sujith3179** [comment]
PLease review , I added a funtion

**Review by Banpreet123 — CHANGES_REQUESTED** [review]
Changes look good to me. Can be merged.

**Review by Banpreet123 — APPROVED** [review]

**Review by vishnuchalla — COMMENTED** [review]
Code changes look good to me. Is there any way we can test the working of this functionality? Some test results for testing steps in the description would be helpful.

**Comment by sujith3179** [comment]
> Code changes look good to me. Is there any way we can test the working of this functionality? Some test results for testing steps in the description would be helpful.

Yes,I added a test case for the function. Please review

**Comment by vishnuchalla** [comment]
> > Code changes look good to me. Is there any way we can test the working of this functionality? Some test results for testing steps in the description would be helpful.
> 
> Yes,I added a test case for the function. Please review

I was referring to the functional test cases, if there are any please add them or else let know how this can be tested with the code changes further.

**Review by vishnuchalla — APPROVED** [review]

**Review by indu2407 — APPROVED** [review]
code changes looks good

**Pull request merged**
